### ISSUE TITLE
Failed to import cnucnu fetcher. cnucnu module missing?

### ISSUE THREAD

**Issue by chkumar246** [yac/verwatch#7]
[chandankumar@dhcp201-127 verwatch]$ verw --help
Failed to import cnucnu fetcher. cnucnu module missing?
Usage: verwatch [options] [PACKAGE_REGEX]

Show versions of packages matched by PACKAGE_REGEX.

Arguments:
  PACKAGE_REGEX   Only packages matching this regular expression will be
                  listed/updated.

Options:
  -p CONF --package-conf=CONF   Use package configuration file CONF.
                                Default: "default"
                                Maps to: /home/chandankumar/.verwatch/packages/CONF.yaml
  -r REGEX --release=REGEX      Only releases matching regular expression REGEX
                                will be listed/updated.
  -u --update                   Update version cache before listing versions.
  -U --update-only              Update version cache and exit.
  -d --update-diff              Update version cache and print version changes.
  -c --show-commands            Show commands used to obtain versions.
  -H --html                     Output standalone styled HTML page.
  --html-embed                  Output raw embeddable HTML.
  --no-color                    Don't use colors in terminal output.
  --version                     Print verwatch version and exit.
  -h --help                     Print this help and exit.

Paths:
  verwatch base      /home/chandankumar/.verwatch
  package configs    /home/chandankumar/.verwatch/packages
  plugins            /home/chandankumar/.verwatch/plugins
  cache              /home/chandankumar/.verwatch/cache

Available version fetchers:
  bodhi
  debug
  distgit
  git
  koji
  repoquery

This issue was poped up while deploying it on Fedora 22 and python 2.7

**Comment by hguemar** [comment]
cnucnu was dropped from F22
http://pkgs.fedoraproject.org/cgit/cnucnu.git/commit/?h=f22
